name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  str:
    required: true
    description: ''
  separator:
    required: false
    description: ''
    default: 'newline'
runs:
  using: 'node12'
  main: 'dist/index.js'
